---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  title: 信息辦公廳
  name: government
  description: 管理單位
spec:
  type: team
  children: []
  members: []
  profile: 
    displayName: 信息辦公廳
    email: gavin.wq.wu@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  title: 交通局
  name: ministry-of-transport
  description: 管理單位
spec:
  type: team
  parent: government
  children: 
    - group:default/foxconn
  members: []
  profile: 
    displayName: 交通局
    email: gavin.wq.wu@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  title: 鴻海富士康
  name: foxconn
  description: 開發單位
spec:
  type: team
  parent: ministry-of-transport
  admin: 
    - user:default/foxconn-gavin
  children: []
  members: 
    - user:default/foxconn-gavin
  profile: 
    displayName: 鴻海富士康
    email: gavin.wq.wu@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  title: Gavin
  name: foxconn-gavin
  description: 開發人員
spec:
  memberOf: []
  profile: 
    displayName: 吳文強
    email: gavin.wq.wu@foxconn.com
