---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  title: 信息辦公廳
  name: government
  description: 管理單位
spec:
  type: team
  children: []
  members: []
  profile: 
    displayName: 信息辦公廳
    email: gavin.wq.wu@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  title: 交通局
  name: ministry-of-transport
  description: 管理單位
spec:
  type: team
  parent: government
  admin:
    - user:default/cain-sw-tsai
  children: 
    - group:default/foxconn
  members: 
    - user:default/cain-sw-tsai
    - user:default/frank-yd-luo
  profile: 
    displayName: 交通局
    email: cain.sw.tsai@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  title: 鴻海富士康
  name: foxconn
  description: 開發單位
spec:
  type: team
  parent: ministry-of-transport
  admin: 
    - user:default/foxconn-gavin
    - user:default/lzing
  children: []
  members: 
    - user:default/foxconn-gavin
    - user:default/quttro
    - user:default/lzing
    - user:default/cain-sw-tsai
    - user:default/Flyingts
    - user:default/OdinHH
    - user:default/Sallyshcehn
    - user:default/evanliuqf
    - user:default/frank-yd-luo
  profile: 
    displayName: 鴻海富士康
    email: zi-ying.liu@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  title: QA测试团队
  name: QA-TESTING
  description: QA测试团队
spec:
  type: team
  children: []
  admin: 
    - user:default/evanliuqf
    - user:default/frank-yd-luo
  members: 
    - user:default/evanliuqf
    - user:default/frank-yd-luo
    - user:default/hughdbhuang
  profile: 
    displayName: QA测试团队
    email: frnk.yd.luo@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  title: Albert
  name: quttro
  description: 開發主管
spec:
  memberOf: []
  profile: 
    displayName: 齊敬仁
    email: albert.cj.chi@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  title: Gavin
  name: foxconn-gavin
  description: 開發人員
spec:
  memberOf: []
  profile: 
    displayName: 吳文強
    email: gavin.wq.wu@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  title: Zi-Ying Liu
  name: lzing
  description: 開發人員
spec:
  memberOf: []
  profile: 
    displayName: 劉梓穎
    email: zi-ying.liu@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  title: Cain Tsai
  name: cain-sw-tsai
  description: 開發人員
spec:
  memberOf: []
  profile: 
    displayName: 蔡憲維
    email: cain.sw.tsai@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  title: Flying
  name: Flyingts
  description: PM
spec:
  memberOf: []
  profile: 
    displayName: 黃天祥
    email: flying.ts.huang@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  title: Odin
  name: OdinHH
  description: PM
spec:
  memberOf: []
  profile: 
    displayName: 王泰元
    email: odin.ty.wang@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  title: Sally
  name: Sallyshcehn
  description: PM
spec:
  memberOf: []
  profile: 
    displayName: 陳萱翰
    email: sally.sh.cehn@foxconn.com
    
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  title: evanliu
  name: evanliuqf
  description: QA
spec:
  memberOf: []
  profile: 
    displayName: 劉啟福
    email: 53880970@qq.com
    
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  title: frank
  name: frank-yd-luo
  description: QA
spec:
  memberOf: []
  profile: 
    displayName: 罗义达
    email: orc4@163.com
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  title: Hugh
  name: hughdbhuang
  description: QA
spec:
  memberOf: []
  profile: 
    displayName: 黄德彬
    email: hugh.db.huang@foxmail.com
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: Maas
  description: |
    交通行動服務（Mobility as a Service, MaaS）是改善疫後交通的重要解決方案。MaaS是一種新的出行服務理念，是指“將不同方式的出行服務（包括公交車、地鐵、網約車、共享單車、出租車、轮渡輪渡等），整合出按需出行的一體化出行服務。
  title: Mobility as a Service MaaS 交通行動服務領域
spec:
  owner: group:foxconn
  
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: PaaS
  description: |
    PaaS是（Platform as a Service）的缩写，是指平台即服务。 把服务器平台作为一种服务提供的商业模式，通过网络进行程序提供的服务称之为SaaS(Software as a Service)，是云计算三种服务模式之一，而云计算时代相应的服务器平台或者开发环境作为服务进行提供就成为了PaaS。
  title: Platform as a Service 平台即服务
spec:
  owner: group:QA-TESTING
