---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  title: 信息辦公廳
  name: government
  description: 管理單位
spec:
  type: team
  children: []
  members: []
  profile: 
    displayName: 信息辦公廳
    email: gavin.wq.wu@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  title: 交通局
  name: ministry-of-transport
  description: 管理單位
spec:
  type: team
  parent: government
  admin:
    - user:default/cain-sw-tsai
  children: 
    - group:default/foxconn
  members: 
    - user:default/cain-sw-tsai
  profile: 
    displayName: 交通局
    email: cain.sw.tsai@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  title: 鴻海富士康
  name: foxconn
  description: 開發單位
spec:
  type: team
  parent: ministry-of-transport
  admin: 
    - user:default/foxconn-gavin
    - user:default/lzing
  children: []
  members: 
    - user:default/foxconn-gavin
    - user:default/lzing
  profile: 
    displayName: 鴻海富士康
    email: zi-ying.liu@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  title: Gavin
  name: foxconn-gavin
  description: 開發人員
spec:
  memberOf: []
  profile: 
    displayName: 吳文強
    email: gavin.wq.wu@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  title: Zi-Ying Liu
  name: lzing
  description: 開發人員
spec:
  memberOf: []
  profile: 
    displayName: 劉梓穎
    email: zi-ying.liu@foxconn.com

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  title: Cain Tsai
  name: cain-sw-tsai
  description: 開發人員
spec:
  memberOf: []
  profile: 
    displayName: 蔡憲維
    email: cain.sw.tsai@foxconn.com
